name: Aparna CI
 dummy text
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: custom-os
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello,World!
