name: Aparna CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Run validator
      uses: aparna-ravindra/workflow-template-validator@v0.4
      with:
        path-to-workflow-yaml: './workflow-templates'
        path-to-properties-json: './workflow-templates'
        path-to-icons: './workflow-templates'
